name: Build

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Use the version of .NET you need

    - name: Install dependencies
      shell: bash
      run: | 
          cd $(git rev-parse --show-toplevel)/src/Hng.Web
          dotnet restore ./Hng.Web.csproj

    - name: Build Application
      shell: bash
      run: | 
          cd $(git rev-parse --show-toplevel)/src/Hng.Web
          dotnet build