name: Print GitHub Object

on:
  push:
    branches:
      - dev

jobs:
  print_github_object:
    runs-on: ubuntu-latest

    steps:
    - name: Print GitHub Context
      run: |
        echo "GitHub Context:"
        echo "Help me" > github-context.json
        cat github-context.json
        echo "${{ github }}" > github-context.json
        cat github-context.json
