name: Print GitHub Object

on:
  push:
    branches:
      - dev

jobs:
  print_github_object:
    runs-on: ubuntu-latest

    steps:
    - name: Print GitHub Context
      run: |
        echo "GitHub Context:"
        echo '{"github": '$(echo '${{ toJson(github) }}')'}' > github-context.json
        cat github-context.json
